typography_spectrum: 0.58893
color:
  brandColors:
    - '#006573'
    - '#102921'
    - '#c75f41'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: UA-74721730-1
  facebook: null
  twitter: null
name: Haught Graphics
cta:
  domain: null
  bucket: null
  version: null
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/b68fb5a2-9af7-4e7a-902e-b66e0cff4658.png'
title: null
purpose: []
