analytics: {}
color:
  brandColors:
    - '#000000'
    - '#481810'
    - '#A05850'
    - '#D86050'
    - '#E06058'
  brandStrength: 0.679276
  lightness: 0.995066
  rhythmicContrast: 0.489309
  saturation: 0.484375
cta: {}
layout_spectrum: 0
name: Haught Graphics
opengraph: {}
purpose: []
typography_spectrum: 0.618421
