name: Haught Graphics
favicon: null
layout_spectrum: 0
typography_spectrum: 0.58893
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74721730-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#006573'
    - '#102921'
    - '#c75f41'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
