analytics: {}
color:
  brandColors:
    - '#dcdacb'
    - '#3b3a38'
    - '#ba8b77'
    - '#cdb99e'
    - '#7c5140'
  brandStrength: 1
  lightness: 0.5
  rhythmicContrast: 0
  saturation: 0.5
cta: {}
layout_spectrum: 0.24367
name: Haught Graphics
opengraph: {}
purpose: []
typography_spectrum: 0.3657
