name: Haught Graphics
favicon: null
layout_spectrum: 0
typography_spectrum: 0.618421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdacb'
    - '#3b3a38'
    - '#ba8b77'
    - '#cdb99e'
    - '#7c5140'
  brandStrength: 0.679276
  lightness: 0.995066
  saturation: 0.484375
  rhythmicContrast: 0.489309
purpose: []
