name: Haught Graphics
favicon: null
layout_spectrum: 0.24773
typography_spectrum: 0.58893
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdacb'
    - '#3b3a38'
    - '#ba8b77'
    - '#cdb99e'
    - '#7c5140'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
